config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'prototypes#index'
  resources :prototypes do
    resources :comments, only: [:show, :create, :edit, :destroy, :update]
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]
  resources :tags, only: [:index, :show]
end

app/models/captured_image.rb
class CapturedImage < ActiveRecord::Base
  belongs_to :prototype

  mount_uploader :content, PrototypeImageUploader

  enum status: %i(main sub)

  validates :content,
            :status,
            presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :prototype, counter_cache: :likes_count
  belongs_to :user
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :captured_images, dependent: :destroy
  has_many :prototype_tags, dependent: :destroy
  has_many :tags, through: :prototype_tags
  has_many :likes, dependent: :destroy

  accepts_nested_attributes_for :captured_images, reject_if: :reject_sub_images
  accepts_nested_attributes_for :tags

  validates :title,
            :catch_copy,
            :concept,
            presence: true

  def like_user(user_id)
   likes.find_by(user_id: user_id)
  end

  def reject_sub_images(attributed)
    attributed['content'].blank?
  end

  def set_main_thumbnail
    captured_images.main.first.content
  end

  def posted_date
    created_at.strftime('%b %d %a')
  end

  def save_tags(saveprototype_tags)
    current_tags = Tag.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - saveprototype_tags
    new_tags = saveprototype_tags - current_tags

    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end

    new_tags.each do |new_name|
      post_tag = Tag.find_or_create_by(name:new_name)
      self.tags << post_tag
    end

  end

end

app/models/prototype_tag.rb
class PrototypeTag < ActiveRecord::Base
  belongs_to :tag
  belongs_to :prototype
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :prototype_tags, dependent: :destroy
  has_many :prototypes, through: :prototype_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, UserImageUploader

  has_many :prototypes
  has_many :comments

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :profile, :position, :occupation, :avatar])

    devise_parameter_sanitizer.permit(:account_update, keys:[:name, :profile, :position, :occupation, :avatar])
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    if user_signed_in?
      @comment = Comment.includes(:user).new(content: comment_params[:content], prototype_id: comment_params[:prototype_id], user_id: current_user.id)
      if @comment.save
        respond_to do |format|
          format.html { prototype_comments_path(@comment) }
          format.json
        end
      end
    else
      redirect_to new_user_session_path
    end
  end

  def edit
    @comment = Comment.includes(:user).find(comment_params[:id])
  end

  def show
    @comment = Comment.includes(:user).find(comment_params[:id])
  end

  def destroy
    deletingComment = Comment.find(comment_params[:id])
    @comment = deletingComment
    if @comment.user_id == current_user.id
      deletingComment.destroy
    end
  end

  def update
    @comment = Comment.find(comment_params[:id])
    if @comment.user_id == current_user.id
      @comment.update( content: comment_params[:content] )
    end
  end

  private
  def comment_params
    params.permit(:id, :content, :prototype_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post

  def create
    @like = Like.create(user_id: current_user.id, prototype_id: params[:prototype_id])
    @likes = Like.where(prototype_id: params[:prototype_id])
    @prototype.reload
  
    # render "show"
    # redirect_to :root, notice: 'like was successfully created'
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, prototype_id: params[:prototype_id])
    like.destroy
    @likes = Like.where(prototype_id: params[:prototype_id])
    @prototype.reload
    # render "show"
    # redirect_to :root, notice: 'like was successfully deleted'
  end

  private

  def set_post
    @prototype = Prototype.find(params[:prototype_id])
  end

end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :set_prototype, only: [:show, :edit, :update]

  def index
    @prototypes = Prototype.all.page(params[:page]).per(5)
  end

  def new
    @prototype = Prototype.new
    @prototype.captured_images.build
    @prototype.tags.build
  end

  def create
    @prototype = Prototype.new(prototype_params)
    if @prototype.save
      redirect_to :root, notice: 'New prototype was successfully created'
    else
      redirect_to ({ action: new }), alert: 'YNew prototype was unsuccessfully created'
    end
  end

  def show
    @comments = @prototype.comments.order('created_at DESC').includes(:user)
  end

  def edit
  end

  def update
    # binding.pry
    if @prototype[:user_id] == current_user.id
      if @prototype.update(prototype_params)
        flash.now[:flash] = "編集しました"
        render :index
      else
        render :edit, alert: 'prototype was unsuccessfully updated'
      end
      render :edit
    end
  end

  def destroy
    prototype = Prototype.find(params[:id])
    if prototype.user_id == current_user.id
      prototype.destroy
    end
  end

  private

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end

  def prototype_params
    params.require(:prototype).permit(
      :title,
      :catch_copy,
      :concept,
      :user_id,
      captured_images_attributes: [:content, :status],
      tags_attributes: [:name]
    )
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
    @prototypes = @tag.prototypes
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @prototypes = @user.prototypes
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to :root, notice: 'Your user infomation was successfully updated'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :position,
      :profile,
      :occupation,
      :avatar
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" =>  "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' =>  true
    = javascript_include_tag 'application', 'data-turbolinks-track' =>  true
    = csrf_meta_tags
  %body
    = flash[:flash]
    = render "shared/header"
    = render "shared/messages"
    = yield
    = render "shared/footer"

app/views/likes/_like.html.haml
- if user_signed_in?
  - unless @prototype.like_user(current_user.id).blank?
    = link_to prototype_like_path(prototype_id: @prototype.id ,id: @prototype.likes[0].id), method: :delete, remote: true do
      .vertical_like
        %p
          = image_tag("redheart.png") 
          LIKE
          = @prototype.likes_count
  - else
    = link_to prototype_likes_path(@prototype.id), method: :post, remote: true do
      .vertical_like
        %p
          = image_tag("grayheart.png") 
          LIKE
          = @prototype.likes_count

- else
  - if @prototype.likes_count > 0
    .vertical_like
      %p
        = image_tag("redheart.png") 
        LIKE
        = @prototype.likes_count
  - else
    .vertical_like
      %p
        = image_tag("grayheart.png") 
        LIKE
        = @prototype.likes_count




/ - if user_signed_in?
/   - if @prototype.like_user(current_user.id)
/     = button_to prototype_like_path(prototype_id: @prototype.id), method: :delete, id: "like-buttons", remote: true do
/       = image_tag("icons8-heart-outline-30.png")
/       %span
/         LIKE
/         = @prototype.likes_count
/   - else
/     = button_to prototype_likes_path(@prototype), id: "like-buttons", remote: true do
/       = image_tag("icons8-heart-outline-40.png")
/       %span
/         LIKE
/         = @prototype.likes_count
/ - else
/   = image_tag("icon_heart.svg")
/   %span
/     LIKE
/     = @prototype.likes_count

app/views/likes/create.js.haml
// $("#like-buttons").html("<%= j(render 'like', locals: { prototypes: @prototypes, likes: @likes, like: @like}) %>")
// $("#like-buttons").html("#{j(render 'like', locals: { prototypes: @prototypes, likes: @likes, like: @like})}")
$('#likes_buttons_#{@prototype.id}').html("#{j(render partial: 'likes/like', locals: {prototype: @prototype})}");

app/views/likes/destroy.js.haml
$('#likes_buttons_#{@prototype.id}').html("#{j(render partial: 'likes/like', locals: {prototype: @prototype})}");

app/views/prototypes/_comment.html.haml
.comment_wrapper
  .comment_left
    = image_tag(comment.user.avatar.thumb, alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
    = link_to comment.user.name, user_path(comment.user)

  .comment_right{id: comment.id}
    .comment_text
      = comment.content
    -if user_signed_in?
      -if current_user.id == comment.user_id
        = link_to 'Edit', "/prototypes/#{@prototype.id}/comments/#{comment.id}/edit", class: 'btn-default btn comment-edit'
  .comment_bottom

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    = link_to image_tag(prototype.set_main_thumbnail), prototype_path(prototype)
    .caption
      %h3
        = prototype.title
      .proto-meta
        .proto-user
          = link_to prototype.user.name, user_path(prototype.user)
        .proto-posted
          = prototype.posted_date

      .vertical_like
        %p
          - if (prototype.likes_count.nil?)||(prototype.likes_count == 0)
            = image_tag("grayheart.png") 
            LIKE
            = 0
          -else
            = image_tag("redheart.png") 
            LIKE
            = prototype.likes_count

app/views/prototypes/destroy.html.haml
.success
  %p Deleted!
  %a{ class: "btn-default btn" ,:href => '/'} 一覧

app/views/prototypes/edit.html.haml
.container.proto-new
  = form_for (@prototype) do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true, placeholder: "Input Title"
      .row
        .col-md-12
          %h4 Main Thumbnail
          .cover-image-upload#main_image_uploader
            = f.fields_for :captured_images do |image|
              %img
              = image.file_field :content, required: true
              = image.hidden_field :status, value: "main"
        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group
            - 3.times do |i|
              %li.list-group-item.col-md-4
                .image-upload
                  = f.fields_for :captured_images do |image|
                    %img
                    = image.file_field :content
                    = image.hidden_field :status, value: "sub"
      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Input Concept"
      .row.text-center.proto-btn
        = f.submit "UPDATE", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/index.html.haml
/ - binding.pry
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", "#"
        %li.btn-default.btn-popular
          = link_to "Newest", "#"
      = link_to "VIEW TAGS", tags_path, class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render partial: 'prototype', collection: @prototypes

.text-center
  =paginate(@prototypes)

app/views/prototypes/new.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true, placeholder: "Input Title"
      .row
        .col-md-12
          %h4 Main Thumbnail
          .cover-image-upload#main_image_uploader
            = f.fields_for :captured_images do |image|
              %img
              = image.file_field :content, required: true
              = image.hidden_field :status, value: "main"
        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group
            - 3.times do |i|
              %li.list-group-item.col-md-4
                .image-upload
                  = f.fields_for :captured_images do |image|
                    %img
                    = image.file_field :content
                    = image.hidden_field :status, value: "sub"
      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Input Concept"
        .col-md-12
          %h4 Tag List
          .row
            - 3.times do |i|
              .col-md-3
                = f.fields_for :tags do |tag|
                  = tag.text_field :name, placeholder: "ex)web"
              / = f.text_field :tags, :name, require: true, placeholder: "ex)web"
            / .col-md-3
            /   = f.text_field :tags, require: true, placeholder: "ex)Rails"
            / .col-md-3
            /   = f.text_field :tags, require: true, placeholder: "ex)UI/UX"
      .row.text-center.proto-btn
        = f.submit "PUBLISH", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to user_path(@prototype.user) do
            = image_tag(@prototype.user.avatar.thumb, alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            by
            = link_to "#{@prototype.user.name}", user_path(@prototype.user)
            .degree
              = @prototype.user.position

    / = render partial: 'likes/like', locals: { prototype: @prototypes }

  %div{:id => "likes_buttons_#{@prototype.id}"}
    = render partial: 'likes/like', locals: { prototype: @prototype, likes: @likes}



    / - if user_signed_in?
    /   - if @prototype.like_user(current_user.id)
    /     = button_to prototype_like_path(prototype_id: @prototype.id), method: :delete, id: "like-buttons", remote: true do
    /       = image_tag("icons8-heart-outline-30.png")
    /       %span
    /         = @prototype.likes_count
    /   - else
    /     = button_to prototype_likes_path(@prototype), id: "like-buttons", remote: true do
    /       = image_tag("icons8-heart-outline-40.png")
    /       %span
    /         = @prototype.likes_count
    / - else
    /   = image_tag("icon_heart.svg")
    /   %span
    /     = @prototype.likes_count


  .col-md-3
    %h4 User Action
    %ul.proto-tag-list.list-inline
      %li
        = link_to '削除', "/prototypes/#{@prototype.id}", method: :delete, class: 'btn-default btn'
      %li
        = link_to '編集', edit_prototype_path, class: 'btn-default btn'

  .row
    .col-md-9.image-box
      = image_tag(@prototype.set_main_thumbnail.large, class: 'img-responsive img-size-fix', style: "margin: 0 auto;")
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.captured_images.sub.each do |image|
          %li.list-group-item
            = image_tag(image.content, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.catch_copy
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        - @prototype.tags.each do |tag|
          %li
            %a{href: "/tags/#{tag.id}", class: "btn btn-default"}
              = tag.name

  .proto-comments
    %h4 COMMENT FORM
    .form_wrapper
      -if user_signed_in?
        = form_tag("/prototypes/#{@prototype.id}/comments", method: :post, id: "new_comment") do
          %textarea{cols: "30", name: "content", placeholder: "Post A Comment !!", rows: "2", class: "comment_form", maxlength: '200'}
          %input{type: "submit", value: "SEND", class: "send_btn "}
      -else
        = form_tag("/prototypes/#{@prototype.id}/comments", method: :post) do
          %textarea{cols: "30", name: "content", placeholder: "Post A Comment !!", rows: "2", class: "comment_form", maxlength: '45'}
          %input{type: "submit", value: "SEND", class: "send_btn redirect"}
    %h4 COMMENTS
    .comments_area{style: "width:100%;height:600px;overflow:auto;"}
      -if @comments
        = render partial: "comment", collection: @comments

app/views/shared/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.

app/views/shared/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    .navbar-brand
      = link_to image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px"), root_path
    .navbar-collapse.collapse.navbar-responsive-collapse
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            = link_to "#", class: 'dropdown-toggle', role: 'button', 'aria-expanded' =>  'false', 'data-toggle' => 'dropdown' do
              #{current_user.name}
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to 'Edit', edit_user_path(current_user)
              %li
                = link_to 'My Page', user_path(current_user)
              %li
                = link_to 'Logout', destroy_user_session_path, method: :delete
          %li
            .btn.btn-default
              = link_to "New Photo", new_prototype_path, style: "color: #337ab7;"
      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'Get Started', new_user_session_path

app/views/shared/_messages.html.haml
- flash.each do |key, value|
  - if value == notice
    = content_tag(:div, value, class: "alert alert--success")
  - if value == alert
    = content_tag(:div, value, class: "alert alert--danger")

app/views/tags/index.html.haml
- @tags.each do |tag|
  = link_to tag.name, tag_path(tag)

app/views/tags/show.html.haml
- @prototypes.each do |prototype|
  = link_to prototype.title, prototype_path(prototype)

app/views/users/edit.html.haml
.container.user-new.clearfix
  = form_for @user do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h2 Edit
          .user-name_image.row
            .user-name.col-md-10
              = f.text_field :name, placeholder: "Input Username", autofocus: true, required: true
            .user-image.col-md-2
              %img{ style: "" }
              = f.file_field :avatar
          .user-email
            = f.text_field :email, placeholder: "Input Email", required: true
        .col-md-12
          %h4 Position
          .user-user-member.row
            .user-name.col-md-12
              = f.text_field :position, placeholder: "Input Position"
          %h4 Profile
          .user-user-profile.row
            .user-name.col-md-12
              = f.text_area :profile, placeholder: "Input Profile", size:"30×4"
          %h4 Occupation
          .user-name_image.row
            .user-name.col-md-12
              = f.text_area :occupation, placeholder: "Input Occupation", size: "30×4"
        .row.text-center.user-btn
          .actions
            = f.submit "SAVE", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        = image_tag(@user.avatar.thumb, alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
      .media-body
        %h4#top-aligned-media.media-heading
          = @user.name
          %span.label.label-default.project-number
            29
            %i Projects
        .proto-user
          %span.degree= @user.position
        .row
          .col-md-6
            %h4 Profile
            %p= @user.profile
          .col-md-6
            %h4 Occupation
            %p= @user.occupation
.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes